name: Release

on:
  release:
    types:
      - published
  push:
    branches:
      - test-release

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.event_name == 'release'

    steps:
      - name: Build, test, and publish (release)
        uses: legreq/tsdev/.github/actions/build-test-publish@main
        with:
          secrets: ${{ toJSON(secrets) }}
          vars: ${{ toJSON(vars) }}

  test:
    runs-on: ubuntu-latest

    if: github.event_name != 'release'

    steps:
      - name: Build, test, and publish (test)
        uses: legreq/tsdev/.github/actions/build-test-publish@test-release
        with:
          secrets: ${{ toJSON(secrets) }}
          vars: ${{ toJSON(vars) }}
