name: Release

on:
  release:
    types:
      - published
  push:
    branches:
      - test-release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check event
        uses: legreq/tsdev/.github/workflows/_release@main
