name: Release

on:
  release:
    types:
      - published
  push:
    branches:
      - test-release

jobs:
  release:
      uses: legreq/tsdev/.github/workflows/_release.yml@main
      secrets: inherit
